### ISSUE TITLE
[FEATURE] Support spaces as well in keyspaceTable list

### ISSUE THREAD

**Issue by cscetbon** [instaclustr/esop#43]
**Is your feature request related to a problem? Please describe.**
The goal is to make the specification of tables simpler

**Describe the solution you'd like**
Instead of specifying `k1.t1,k2.t2` we should be able to specify as well `k1.t1 k2.t2`

**Additional context**
Instead of doing https://github.com/instaclustr/esop/blob/72aa67a61582f484fe1f9f7b020d3b9b14d3b520/src/main/java/com/instaclustr/esop/impl/DatabaseEntities.java#L110-L112 it could be replaced by 
```java
final String[] keyspaceTablePairs = entities.split("[\\s,]+");
```

**Comment by smiklosovic** [comment]
supported from 1.0.7 included
