### ISSUE TITLE
[FEATURE] Add `minio` as a cloud provider/protocol option

### ISSUE THREAD

**Issue by zachlipp** [instaclustr/esop#44]
**Is your feature request related to a problem? Please describe.**

I am using esop to backup to a minio deployment as in #14. `minio` uses path-style s3 routing, so I cannot use the `s3://` protocol. I can use path-style routing with the `oracle://` protocol; however, this implementation is confusing to developers who aren't familiar with this project and/or s3 providers.

**Describe the solution you'd like**
I would like an additional s3 protocol for `minio`. This could largely duplicate code already used in `../esop/s3/oracle` as both providers use path-style routing. 

**Describe alternatives you've considered**
Using the  `oracle://` protocol and setting  `awsendpoint` in the access secret to the minio endpoint works.

**Comment by smiklosovic** [comment]
hi @zachlipp ,

could you please try latest `master` branch? 

I just added this https://github.com/instaclustr/esop/commit/fce2926b698eb74859c297078d5af55b77eae7ec

Surprisingly it should do the job :)

Please let me know and I can release it afterwards.

You build it like `mvn clean install -DskipTests`

**Comment by zachlipp** [comment]
Thank you for the quick turnaround!

I am running into an error:
```
java.lang.IllegalStateException: Available storage providers: [s3, azure, gcp, file, oracle, ceph]
```

Looks like this might be from `minio` not being present in `storageProviders.toArray()`, see https://github.com/instaclustr/esop/blob/master/src/main/java/com/instaclustr/esop/impl/AbstractOperationRequest.java#L133

**Comment by cscetbon** [comment]
Hey @zachlipp you can use the s3 protocol to access minio as long as you enable the virtual hosting mode which is activated by setting MINIO_DOMAIN environment variable. See the Domain section at https://docs.minio.io/docs/minio-server-configuration-guide.html

**Comment by smiklosovic** [comment]
Thanks @cscetbon , if that is ok for @zachlipp to use, I would consider this to be a non-issue and we might just close it. Please @zachlipp , return to this ticket confirming it works with Cyril's suggestion.

**Comment by zachlipp** [comment]
Thanks for the suggestion @cscetbon, I should have mentioned I already tried it.

The issue here is that minio is hosted within the same Kubernetes cluster as the cassandra pods, and we'd like to keep traffic internal, so there isn't a minio hostname. Even if I pass the appropriate `MINIO_DOMAIN` argument, the request cannot route to it because there aren't internal DNS rules for the subdomain.

I see two ways around this:

- Use the `MINIO_DOMAIN` envvar and hard-code the pod's subdomain and hostname and route to the pod using a headless service, as in [here](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields). I got this to work. I prefer not to use this implementation as it only works for one bucket name and it creates more extraneous Kubernetes objects.
- Use the `MINIO_DOMAIN` envvar and write custom DNS rules for routing to the minio service. I rejected this as too complicated, but this is the implementation I like the idea of the most.

While minio can use virtual host routing with the `MINIO_DOMAIN` environment variable, that variable doesn't play well with Kubernetes. I would still prefer an explicit `minio://` protocol but I understand if you don't want to support that in this project.

**Comment by smiklosovic** [comment]
@zachlipp would you mind to try this one? https://github.com/instaclustr/esop/pull/46

**Comment by smiklosovic** [comment]
Part of 1.0.8

**Comment by zachlipp** [comment]
Thank you!
